### ISSUE TITLE
i trusted you i used your db for my propjet and now its glitching now working idk its broke no errors it wont read data 

### ISSUE THREAD

**Issue by iiMu7aMMaD** [barbarbar338/bookman#6]

**Comment by iiMu7aMMaD** [comment]
can you give me a old version of it where its working or is there a way to transform the data into the quick.db?

**Comment by iiMu7aMMaD** [comment]
i'm sorry but pls fix it

**Comment by barbarbar338** [comment]
Are you using async await?

**Comment by barbarbar338** [comment]
i think your problem is fixed.

**Comment by iiMu7aMMaD** [comment]
Yes i'm still not working like it should.

When i type 
await db.set("fo","bar")
console.log(await db.get("fo"));
Returns nothing I don't what is going on but I tried quick.db and it worked like it should return bar.


and when i try to go back to older version where bookman worked i can't.

Please make it so i can still use old versions.

**Comment by barbarbar338** [comment]
it works awesome for me

![image](https://user-images.githubusercontent.com/35371155/122403285-ed602300-cf86-11eb-8295-75c1e65631a1.png)

**Comment by iiMu7aMMaD** [comment]
I tried to reinstall it. but it won't work.

**Comment by barbarbar338** [comment]
show me you logs. Also are you using Linux based OS?
